import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query"; import {listContentFeed,createContent,toggleReaction,toggleSave,votePoll,listContentComments,addContentComment,repostContent} from "./api";
export function useContentFeed(roomId?:string|null,authorId?:string|null){return useQuery({queryKey:["content-feed",roomId??null,authorId??null],queryFn:()=>listContentFeed(roomId??null,authorId??null),staleTime:15_000,refetchOnReconnect:true});}
export function useCreateContent(){const qc=useQueryClient();return useMutation({mutationFn:(v:{roomId:string|null;kind:string;title:string|null;body:string|null;metadata?:Record<string,unknown>})=>createContent(v.roomId,v.kind,v.title,v.body,v.metadata??{}),onSuccess:()=>qc.invalidateQueries({queryKey:["content-feed"]})});}
export function useToggleContentReaction(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,reaction}:{contentId:string;reaction:string})=>toggleReaction(contentId,reaction),onSuccess:()=>qc.invalidateQueries({queryKey:["content-feed"]})});}
export function useToggleContentSave(){const qc=useQueryClient();return useMutation({mutationFn:toggleSave,onSuccess:()=>qc.invalidateQueries({queryKey:["content-feed"]})});}
export function useVotePoll(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,optionId}:{contentId:string;optionId:string})=>votePoll(contentId,optionId),onSuccess:()=>qc.invalidateQueries({queryKey:["content-feed"]})});}

export function useContentComments(id:string){return useQuery({queryKey:["content",id,"comments"],queryFn:()=>listContentComments(id),enabled:!!id,staleTime:15_000});}
export function useAddContentComment(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,body,parentId}:{contentId:string;body:string;parentId?:string|null})=>addContentComment(contentId,body,parentId??null),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["content",v.contentId,"comments"]})});}
export function useRepostContent(){const qc=useQueryClient();return useMutation({mutationFn:({contentId,roomId}:{contentId:string;roomId?:string|null})=>repostContent(contentId,roomId??null),onSuccess:()=>qc.invalidateQueries({queryKey:["content-feed"]})});}
