import {useEffect} from "react"; import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query"; import {listRooms,joinRoom,sendRoomMessage,listRoomMessages,listOnlineRoomMembers,listRoomCoHosts,replyToRoomMessage,sendRoomSticker} from "./api"; import {subscribeToRoomMessages,removeRealtimeChannel} from "@/lib/realtime";
export function useRooms(){return useQuery({queryKey:["rooms"],queryFn:listRooms,staleTime:30_000,refetchOnReconnect:true});}
export function useRoomMessages(roomId:string){const qc=useQueryClient();const query=useQuery({queryKey:["room-messages",roomId],queryFn:()=>listRoomMessages(roomId),enabled:!!roomId,staleTime:5_000,refetchOnReconnect:true});useEffect(()=>{if(!roomId)return;const channel=subscribeToRoomMessages(roomId,()=>qc.invalidateQueries({queryKey:["room-messages",roomId]}));return()=>{void removeRealtimeChannel(channel)}},[roomId,qc]);return query;}
export function useRoomOnlineMembers(roomId:string){return useQuery({queryKey:["room-online-members",roomId],queryFn:()=>listOnlineRoomMembers(roomId),enabled:!!roomId,staleTime:15_000,refetchOnReconnect:true});}
export function useRoomCoHosts(roomId:string){return useQuery({queryKey:["room-cohosts",roomId],queryFn:()=>listRoomCoHosts(roomId),enabled:!!roomId,staleTime:30_000});}
export function useJoinRoom(){const qc=useQueryClient();return useMutation({mutationFn:joinRoom,onSuccess:()=>qc.invalidateQueries({queryKey:["rooms"]})});}
export function useSendRoomMessage(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,body}:{roomId:string;body:string})=>sendRoomMessage(roomId,body),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages",v.roomId]})});}
export function useReplyToRoomMessage(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,messageId,body}:{roomId:string;messageId:string;body:string})=>replyToRoomMessage(roomId,messageId,body),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages",v.roomId]})});}
export function useSendRoomSticker(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,stickerId}:{roomId:string;stickerId:string})=>sendRoomSticker(roomId,stickerId),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages",v.roomId]})});}
