import {useEffect} from "react"; import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query"; import {listRooms,joinRoom,sendRoomMessage,listRoomMessages,listOnlineRoomMembers,listRoomCoHosts,replyToRoomMessage,sendRoomSticker,toggleRoomMessageReaction,markMessageRead,markRoomRead,setRoomMessageMentions,setRoomPinnedMessage,setRoomLock,setRoomChatSettings,moderateRoomMember,kickRoomMember,moderateRoomMessage,strikeRoomMember,listRoomReports,createRoomReport,getMyRoomMembership,listRoomMembers,setRoomCoHost,updateRoomReport,listRoomModerationHistory,requestRoomCoHost,acceptRoomCoHostRequest,declineRoomCoHostRequest,cancelRoomCoHostRequest} from "./api"; import {subscribeToRoomMessages,removeRealtimeChannel} from "@/lib/realtime";
export function useRooms(){return useQuery({queryKey:["rooms"],queryFn:listRooms,staleTime:30_000,refetchOnReconnect:true});}
export function useRoomMessages(roomId:string,enabled=true){const qc=useQueryClient();const query=useQuery({queryKey:["room-messages",roomId],queryFn:()=>listRoomMessages(roomId),enabled:!!roomId&&enabled,staleTime:5_000,refetchOnReconnect:true});useEffect(()=>{if(!roomId||!enabled)return;const channel=subscribeToRoomMessages(roomId,()=>qc.invalidateQueries({queryKey:["room-messages",roomId]}));return()=>{void removeRealtimeChannel(channel)}},[roomId,enabled,qc]);return query;}
export function useRoomOnlineMembers(roomId:string){return useQuery({queryKey:["room-online-members",roomId],queryFn:()=>listOnlineRoomMembers(roomId),enabled:!!roomId,staleTime:15_000,refetchOnReconnect:true});}
export function useRoomCoHosts(roomId:string){return useQuery({queryKey:["room-cohosts",roomId],queryFn:()=>listRoomCoHosts(roomId),enabled:!!roomId,staleTime:30_000});}
export function useJoinRoom(){const qc=useQueryClient();return useMutation({mutationFn:joinRoom,onSuccess:(_,roomId)=>{qc.invalidateQueries({queryKey:["rooms"]});qc.invalidateQueries({queryKey:["room-membership",roomId]});}});}
export function useSendRoomMessage(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,body}:{roomId:string;body:string})=>sendRoomMessage(roomId,body),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages",v.roomId]})});}
export function useReplyToRoomMessage(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,messageId,body}:{roomId:string;messageId:string;body:string})=>replyToRoomMessage(roomId,messageId,body),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages",v.roomId]})});}
export function useToggleRoomMessageReaction(){const qc=useQueryClient();return useMutation({mutationFn:({messageId,reaction}:{messageId:string;reaction:string})=>toggleRoomMessageReaction(messageId,reaction),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages"]})});}
export function useMarkMessageRead(){return useMutation({mutationFn:markMessageRead});}
export function useMarkRoomRead(){return useMutation({mutationFn:markRoomRead});}
export function useSetRoomMessageMentions(){return useMutation({mutationFn:({messageId,userIds}:{messageId:string;userIds:string[]})=>setRoomMessageMentions(messageId,userIds)});}
export function useSendRoomSticker(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,stickerId}:{roomId:string;stickerId:string})=>sendRoomSticker(roomId,stickerId),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages",v.roomId]})});}

export function useSetRoomPinnedMessage(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,messageId}:{roomId:string;messageId:string|null})=>setRoomPinnedMessage(roomId,messageId),onSuccess:()=>qc.invalidateQueries({queryKey:["rooms"]})});}
export function useSetRoomLock(){const qc=useQueryClient();return useMutation({mutationFn:({roomId,locked,reason}:{roomId:string;locked:boolean;reason?:string|null})=>setRoomLock(roomId,locked,reason??null),onSuccess:()=>qc.invalidateQueries({queryKey:["rooms"]})});}
export function useSetRoomChatSettings(){const qc=useQueryClient();return useMutation({mutationFn:(v:{roomId:string;announcement:string|null;viewOnly:boolean;membersCanInvite:boolean})=>setRoomChatSettings(v.roomId,v.announcement,v.viewOnly,v.membersCanInvite),onSuccess:()=>qc.invalidateQueries({queryKey:["rooms"]})});}
export function useModerateRoomMember(){const qc=useQueryClient();return useMutation({mutationFn:(v:{roomId:string;targetUserId:string;action:string;durationMinutes:number|null;reason:string})=>moderateRoomMember(v.roomId,v.targetUserId,v.action,v.durationMinutes,v.reason),onSuccess:(_,v)=>{qc.invalidateQueries({queryKey:["room-online-members",v.roomId]});qc.invalidateQueries({queryKey:["rooms"]})}});}
export function useKickRoomMember(){const qc=useQueryClient();return useMutation({mutationFn:(v:{roomId:string;targetUserId:string;allowRejoin:boolean;reason:string})=>kickRoomMember(v.roomId,v.targetUserId,v.allowRejoin,v.reason),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-online-members",v.roomId]})});}
export function useModerateRoomMessage(){const qc=useQueryClient();return useMutation({mutationFn:(v:{messageId:string;action:string;reason:string})=>moderateRoomMessage(v.messageId,v.action,v.reason),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-messages"]})});}
export function useStrikeRoomMember(){const qc=useQueryClient();return useMutation({mutationFn:(v:{roomId:string;targetUserId:string;durationMinutes:number;reason:string})=>strikeRoomMember(v.roomId,v.targetUserId,v.durationMinutes,v.reason),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:["room-online-members",v.roomId]})});}
export function useRoomReports(roomId:string,status="open"){return useQuery({queryKey:["room-reports",roomId,status],queryFn:()=>listRoomReports(roomId,status),enabled:!!roomId,staleTime:10_000});}
export function useCreateRoomReport(){return useMutation({mutationFn:(v:{roomId:string;messageId?:string|null;reportedUserId?:string|null;reason:string})=>createRoomReport(v.roomId,v.messageId??null,v.reportedUserId??null,v.reason)});}

export function useMyRoomMembership(roomId:string){return useQuery({queryKey:["room-membership",roomId],queryFn:()=>getMyRoomMembership(roomId),enabled:!!roomId,staleTime:15_000});}

export function useRoomMembers(roomId:string){return useQuery({queryKey:["room-members",roomId],queryFn:()=>listRoomMembers(roomId),enabled:!!roomId,staleTime:30_000});}
export function useSetRoomCoHost(){const qc=useQueryClient();return useMutation({mutationFn:(v:{roomId:string;targetUserId:string;enabled:boolean})=>setRoomCoHost(v.roomId,v.targetUserId,v.enabled),onSuccess:(_,v)=>{qc.invalidateQueries({queryKey:["room-cohosts",v.roomId]});qc.invalidateQueries({queryKey:["room-members",v.roomId]})}});}

export function useRoomModerationHistory(roomId:string){return useQuery({queryKey:["room-moderation-history",roomId],queryFn:()=>listRoomModerationHistory(roomId),enabled:!!roomId,staleTime:15_000});}
export function useRequestRoomCoHost(){return useMutation({mutationFn:(v:{roomId:string;targetUserId:string})=>requestRoomCoHost(v.roomId,v.targetUserId)});}
export function useAcceptRoomCoHostRequest(){return useMutation({mutationFn:acceptRoomCoHostRequest});}
export function useDeclineRoomCoHostRequest(){return useMutation({mutationFn:declineRoomCoHostRequest});}
export function useCancelRoomCoHostRequest(){return useMutation({mutationFn:cancelRoomCoHostRequest});}
export function useUpdateRoomReport(){const qc=useQueryClient();return useMutation({mutationFn:(v:{reportId:string;status:"reviewing"|"resolved"|"dismissed";resolution:string|null})=>updateRoomReport(v.reportId,v.status,v.resolution),onSuccess:()=>qc.invalidateQueries({queryKey:["room-reports"]})});}
